//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_In_ConsoleApp.GSSMSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GSSMSService.ISMSSERVICE")]
    public interface ISMSSERVICE {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/DataManipulationR1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/DataManipulationR1V1Response")]
        WCF_In_ConsoleApp.GSSMSService.DataManipulationR1V1Response DataManipulationR1V1(WCF_In_ConsoleApp.GSSMSService.DataManipulationR1V1Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/DataManipulationR1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/DataManipulationR1V1Response")]
        System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.DataManipulationR1V1Response> DataManipulationR1V1Async(WCF_In_ConsoleApp.GSSMSService.DataManipulationR1V1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/List1R1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/List1R1V1Response")]
        WCF_In_ConsoleApp.GSSMSService.List1R1V1Response List1R1V1(WCF_In_ConsoleApp.GSSMSService.List1R1V1Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/List1R1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/List1R1V1Response")]
        System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.List1R1V1Response> List1R1V1Async(WCF_In_ConsoleApp.GSSMSService.List1R1V1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/List2R1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/List2R1V1Response")]
        WCF_In_ConsoleApp.GSSMSService.List2R1V1Response List2R1V1(WCF_In_ConsoleApp.GSSMSService.List2R1V1Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/List2R1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/List2R1V1Response")]
        System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.List2R1V1Response> List2R1V1Async(WCF_In_ConsoleApp.GSSMSService.List2R1V1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/List3R1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/List3R1V1Response")]
        WCF_In_ConsoleApp.GSSMSService.List3R1V1Response List3R1V1(WCF_In_ConsoleApp.GSSMSService.List3R1V1Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/List3R1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/List3R1V1Response")]
        System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.List3R1V1Response> List3R1V1Async(WCF_In_ConsoleApp.GSSMSService.List3R1V1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/List4R1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/List4R1V1Response")]
        WCF_In_ConsoleApp.GSSMSService.List4R1V1Response List4R1V1(WCF_In_ConsoleApp.GSSMSService.List4R1V1Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/List4R1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/List4R1V1Response")]
        System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.List4R1V1Response> List4R1V1Async(WCF_In_ConsoleApp.GSSMSService.List4R1V1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/List5R1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/List5R1V1Response")]
        WCF_In_ConsoleApp.GSSMSService.List5R1V1Response List5R1V1(WCF_In_ConsoleApp.GSSMSService.List5R1V1Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/List5R1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/List5R1V1Response")]
        System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.List5R1V1Response> List5R1V1Async(WCF_In_ConsoleApp.GSSMSService.List5R1V1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/ListRecordCountR1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/ListRecordCountR1V1Response")]
        WCF_In_ConsoleApp.GSSMSService.ListRecordCountR1V1Response ListRecordCountR1V1(WCF_In_ConsoleApp.GSSMSService.ListRecordCountR1V1Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/ListRecordCountR1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/ListRecordCountR1V1Response")]
        System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.ListRecordCountR1V1Response> ListRecordCountR1V1Async(WCF_In_ConsoleApp.GSSMSService.ListRecordCountR1V1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/ListR2V1", ReplyAction="http://tempuri.org/ISMSSERVICE/ListR2V1Response")]
        WCF_In_ConsoleApp.GSSMSService.ListR2V1Response ListR2V1(WCF_In_ConsoleApp.GSSMSService.ListR2V1Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/ListR2V1", ReplyAction="http://tempuri.org/ISMSSERVICE/ListR2V1Response")]
        System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.ListR2V1Response> ListR2V1Async(WCF_In_ConsoleApp.GSSMSService.ListR2V1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/UpdateSMSDetails", ReplyAction="http://tempuri.org/ISMSSERVICE/UpdateSMSDetailsResponse")]
        WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsResponse UpdateSMSDetails(WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/UpdateSMSDetails", ReplyAction="http://tempuri.org/ISMSSERVICE/UpdateSMSDetailsResponse")]
        System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsResponse> UpdateSMSDetailsAsync(WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/UpdateSMSDetailsR1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/UpdateSMSDetailsR1V1Response")]
        WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsR1V1Response UpdateSMSDetailsR1V1(WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsR1V1Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/UpdateSMSDetailsR1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/UpdateSMSDetailsR1V1Response")]
        System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsR1V1Response> UpdateSMSDetailsR1V1Async(WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsR1V1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/ListSMSDetailsR1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/ListSMSDetailsR1V1Response")]
        WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR1V1Response ListSMSDetailsR1V1(WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR1V1Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/ListSMSDetailsR1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/ListSMSDetailsR1V1Response")]
        System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR1V1Response> ListSMSDetailsR1V1Async(WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR1V1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/ListSMSDetailsR2V1", ReplyAction="http://tempuri.org/ISMSSERVICE/ListSMSDetailsR2V1Response")]
        WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR2V1Response ListSMSDetailsR2V1(WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR2V1Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/ListSMSDetailsR2V1", ReplyAction="http://tempuri.org/ISMSSERVICE/ListSMSDetailsR2V1Response")]
        System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR2V1Response> ListSMSDetailsR2V1Async(WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR2V1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/ExportToExcelLastRecordR1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/ExportToExcelLastRecordR1V1Response")]
        WCF_In_ConsoleApp.GSSMSService.ExportToExcelLastRecordR1V1Response ExportToExcelLastRecordR1V1(WCF_In_ConsoleApp.GSSMSService.ExportToExcelLastRecordR1V1Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/ExportToExcelLastRecordR1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/ExportToExcelLastRecordR1V1Response")]
        System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.ExportToExcelLastRecordR1V1Response> ExportToExcelLastRecordR1V1Async(WCF_In_ConsoleApp.GSSMSService.ExportToExcelLastRecordR1V1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/ExportCommonWindowToExcelR1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/ExportCommonWindowToExcelR1V1Response")]
        WCF_In_ConsoleApp.GSSMSService.ExportCommonWindowToExcelR1V1Response ExportCommonWindowToExcelR1V1(WCF_In_ConsoleApp.GSSMSService.ExportCommonWindowToExcelR1V1Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/ExportCommonWindowToExcelR1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/ExportCommonWindowToExcelR1V1Response")]
        System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.ExportCommonWindowToExcelR1V1Response> ExportCommonWindowToExcelR1V1Async(WCF_In_ConsoleApp.GSSMSService.ExportCommonWindowToExcelR1V1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/ExportSearchToExcelR1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/ExportSearchToExcelR1V1Response")]
        WCF_In_ConsoleApp.GSSMSService.ExportSearchToExcelR1V1Response ExportSearchToExcelR1V1(WCF_In_ConsoleApp.GSSMSService.ExportSearchToExcelR1V1Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSSERVICE/ExportSearchToExcelR1V1", ReplyAction="http://tempuri.org/ISMSSERVICE/ExportSearchToExcelR1V1Response")]
        System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.ExportSearchToExcelR1V1Response> ExportSearchToExcelR1V1Async(WCF_In_ConsoleApp.GSSMSService.ExportSearchToExcelR1V1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataManipulationR1V1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DataManipulationR1V1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet objDataSet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataSet objDataSetStringInfo;
        
        public DataManipulationR1V1Request() {
        }
        
        public DataManipulationR1V1Request(System.Data.DataSet objDataSet, System.Data.DataSet objDataSetStringInfo) {
            this.objDataSet = objDataSet;
            this.objDataSetStringInfo = objDataSetStringInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DataManipulationR1V1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DataManipulationR1V1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet DataManipulationR1V1Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int intErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] stringOutputResult;
        
        public DataManipulationR1V1Response() {
        }
        
        public DataManipulationR1V1Response(System.Data.DataSet DataManipulationR1V1Result, int intErrorCount, string[] stringOutputResult) {
            this.DataManipulationR1V1Result = DataManipulationR1V1Result;
            this.intErrorCount = intErrorCount;
            this.stringOutputResult = stringOutputResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="List1R1V1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class List1R1V1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string stringExpression;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string stringOrderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intRecordFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int intRecordTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public System.Data.DataSet objDataSetStringInfo;
        
        public List1R1V1Request() {
        }
        
        public List1R1V1Request(string stringExpression, string stringOrderBy, int intRecordFrom, int intRecordTo, System.Data.DataSet objDataSetStringInfo) {
            this.stringExpression = stringExpression;
            this.stringOrderBy = stringOrderBy;
            this.intRecordFrom = intRecordFrom;
            this.intRecordTo = intRecordTo;
            this.objDataSetStringInfo = objDataSetStringInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="List1R1V1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class List1R1V1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet List1R1V1Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int intRecordCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] stringOutputResult;
        
        public List1R1V1Response() {
        }
        
        public List1R1V1Response(System.Data.DataSet List1R1V1Result, int intRecordCount, int intErrorCount, string[] stringOutputResult) {
            this.List1R1V1Result = List1R1V1Result;
            this.intRecordCount = intRecordCount;
            this.intErrorCount = intErrorCount;
            this.stringOutputResult = stringOutputResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="List2R1V1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class List2R1V1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string stringExpression;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string stringOrderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intRecordFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int intRecordTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public System.Data.DataSet objDataSetStringInfo;
        
        public List2R1V1Request() {
        }
        
        public List2R1V1Request(string stringExpression, string stringOrderBy, int intRecordFrom, int intRecordTo, System.Data.DataSet objDataSetStringInfo) {
            this.stringExpression = stringExpression;
            this.stringOrderBy = stringOrderBy;
            this.intRecordFrom = intRecordFrom;
            this.intRecordTo = intRecordTo;
            this.objDataSetStringInfo = objDataSetStringInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="List2R1V1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class List2R1V1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet List2R1V1Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int intRecordCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] stringOutputResult;
        
        public List2R1V1Response() {
        }
        
        public List2R1V1Response(System.Data.DataSet List2R1V1Result, int intRecordCount, int intErrorCount, string[] stringOutputResult) {
            this.List2R1V1Result = List2R1V1Result;
            this.intRecordCount = intRecordCount;
            this.intErrorCount = intErrorCount;
            this.stringOutputResult = stringOutputResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="List3R1V1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class List3R1V1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string stringExpression;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string stringOrderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intRecordFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int intRecordTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public System.Data.DataSet objDataSetStringInfo;
        
        public List3R1V1Request() {
        }
        
        public List3R1V1Request(string stringExpression, string stringOrderBy, int intRecordFrom, int intRecordTo, System.Data.DataSet objDataSetStringInfo) {
            this.stringExpression = stringExpression;
            this.stringOrderBy = stringOrderBy;
            this.intRecordFrom = intRecordFrom;
            this.intRecordTo = intRecordTo;
            this.objDataSetStringInfo = objDataSetStringInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="List3R1V1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class List3R1V1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet List3R1V1Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int intRecordCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] stringOutputResult;
        
        public List3R1V1Response() {
        }
        
        public List3R1V1Response(System.Data.DataSet List3R1V1Result, int intRecordCount, int intErrorCount, string[] stringOutputResult) {
            this.List3R1V1Result = List3R1V1Result;
            this.intRecordCount = intRecordCount;
            this.intErrorCount = intErrorCount;
            this.stringOutputResult = stringOutputResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="List4R1V1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class List4R1V1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string stringExpression;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string stringOrderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intRecordFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int intRecordTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public System.Data.DataSet objDataSetStringInfo;
        
        public List4R1V1Request() {
        }
        
        public List4R1V1Request(string stringExpression, string stringOrderBy, int intRecordFrom, int intRecordTo, System.Data.DataSet objDataSetStringInfo) {
            this.stringExpression = stringExpression;
            this.stringOrderBy = stringOrderBy;
            this.intRecordFrom = intRecordFrom;
            this.intRecordTo = intRecordTo;
            this.objDataSetStringInfo = objDataSetStringInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="List4R1V1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class List4R1V1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet List4R1V1Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int intRecordCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] stringOutputResult;
        
        public List4R1V1Response() {
        }
        
        public List4R1V1Response(System.Data.DataSet List4R1V1Result, int intRecordCount, int intErrorCount, string[] stringOutputResult) {
            this.List4R1V1Result = List4R1V1Result;
            this.intRecordCount = intRecordCount;
            this.intErrorCount = intErrorCount;
            this.stringOutputResult = stringOutputResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="List5R1V1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class List5R1V1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string stringExpression;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string stringOrderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intRecordFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int intRecordTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public System.Data.DataSet objDataSetStringInfo;
        
        public List5R1V1Request() {
        }
        
        public List5R1V1Request(string stringExpression, string stringOrderBy, int intRecordFrom, int intRecordTo, System.Data.DataSet objDataSetStringInfo) {
            this.stringExpression = stringExpression;
            this.stringOrderBy = stringOrderBy;
            this.intRecordFrom = intRecordFrom;
            this.intRecordTo = intRecordTo;
            this.objDataSetStringInfo = objDataSetStringInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="List5R1V1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class List5R1V1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet List5R1V1Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int intRecordCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] stringOutputResult;
        
        public List5R1V1Response() {
        }
        
        public List5R1V1Response(System.Data.DataSet List5R1V1Result, int intRecordCount, int intErrorCount, string[] stringOutputResult) {
            this.List5R1V1Result = List5R1V1Result;
            this.intRecordCount = intRecordCount;
            this.intErrorCount = intErrorCount;
            this.stringOutputResult = stringOutputResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListRecordCountR1V1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListRecordCountR1V1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string tableName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string stringExpression;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string condition;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Data.DataSet objDataSetStringInfo;
        
        public ListRecordCountR1V1Request() {
        }
        
        public ListRecordCountR1V1Request(string tableName, string stringExpression, string condition, System.Data.DataSet objDataSetStringInfo) {
            this.tableName = tableName;
            this.stringExpression = stringExpression;
            this.condition = condition;
            this.objDataSetStringInfo = objDataSetStringInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListRecordCountR1V1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListRecordCountR1V1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ListRecordCountR1V1Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int intRecordCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] stringOutputResult;
        
        public ListRecordCountR1V1Response() {
        }
        
        public ListRecordCountR1V1Response(System.Data.DataSet ListRecordCountR1V1Result, int intRecordCount, int intErrorCount, string[] stringOutputResult) {
            this.ListRecordCountR1V1Result = ListRecordCountR1V1Result;
            this.intRecordCount = intRecordCount;
            this.intErrorCount = intErrorCount;
            this.stringOutputResult = stringOutputResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListR2V1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListR2V1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] stringInputValues;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string stringExpression;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string stringOrderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int intRecordFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int intRecordTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public System.Data.DataSet objDataSetStringInfo;
        
        public ListR2V1Request() {
        }
        
        public ListR2V1Request(string[] stringInputValues, string stringExpression, string stringOrderBy, int intRecordFrom, int intRecordTo, System.Data.DataSet objDataSetStringInfo) {
            this.stringInputValues = stringInputValues;
            this.stringExpression = stringExpression;
            this.stringOrderBy = stringOrderBy;
            this.intRecordFrom = intRecordFrom;
            this.intRecordTo = intRecordTo;
            this.objDataSetStringInfo = objDataSetStringInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListR2V1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListR2V1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ListR2V1Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int intRecordCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] stringOutputResult;
        
        public ListR2V1Response() {
        }
        
        public ListR2V1Response(System.Data.DataSet ListR2V1Result, int intRecordCount, int intErrorCount, string[] stringOutputResult) {
            this.ListR2V1Result = ListR2V1Result;
            this.intRecordCount = intRecordCount;
            this.intErrorCount = intErrorCount;
            this.stringOutputResult = stringOutputResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateSMSDetails", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateSMSDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string stringType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] stringInputValues;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Data.DataSet objDataSetInput;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Data.DataSet objDataSetStringInfo;
        
        public UpdateSMSDetailsRequest() {
        }
        
        public UpdateSMSDetailsRequest(string stringType, string[] stringInputValues, System.Data.DataSet objDataSetInput, System.Data.DataSet objDataSetStringInfo) {
            this.stringType = stringType;
            this.stringInputValues = stringInputValues;
            this.objDataSetInput = objDataSetInput;
            this.objDataSetStringInfo = objDataSetStringInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateSMSDetailsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateSMSDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet UpdateSMSDetailsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int intErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] stringOutputResult;
        
        public UpdateSMSDetailsResponse() {
        }
        
        public UpdateSMSDetailsResponse(System.Data.DataSet UpdateSMSDetailsResult, int intErrorCount, string[] stringOutputResult) {
            this.UpdateSMSDetailsResult = UpdateSMSDetailsResult;
            this.intErrorCount = intErrorCount;
            this.stringOutputResult = stringOutputResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateSMSDetailsR1V1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateSMSDetailsR1V1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string stringType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] stringInputValues;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Data.DataSet objDataSetInput;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Data.DataSet objDataSetStringInfo;
        
        public UpdateSMSDetailsR1V1Request() {
        }
        
        public UpdateSMSDetailsR1V1Request(string stringType, string[] stringInputValues, System.Data.DataSet objDataSetInput, System.Data.DataSet objDataSetStringInfo) {
            this.stringType = stringType;
            this.stringInputValues = stringInputValues;
            this.objDataSetInput = objDataSetInput;
            this.objDataSetStringInfo = objDataSetStringInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateSMSDetailsR1V1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateSMSDetailsR1V1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet UpdateSMSDetailsR1V1Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int intErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] stringOutputResult;
        
        public UpdateSMSDetailsR1V1Response() {
        }
        
        public UpdateSMSDetailsR1V1Response(System.Data.DataSet UpdateSMSDetailsR1V1Result, int intErrorCount, string[] stringOutputResult) {
            this.UpdateSMSDetailsR1V1Result = UpdateSMSDetailsR1V1Result;
            this.intErrorCount = intErrorCount;
            this.stringOutputResult = stringOutputResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListSMSDetailsR1V1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListSMSDetailsR1V1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string stringType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string stringExpression;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string stringOrderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int intRecordFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int intRecordTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public System.Data.DataSet objDataSetStringInfo;
        
        public ListSMSDetailsR1V1Request() {
        }
        
        public ListSMSDetailsR1V1Request(string stringType, string stringExpression, string stringOrderBy, int intRecordFrom, int intRecordTo, System.Data.DataSet objDataSetStringInfo) {
            this.stringType = stringType;
            this.stringExpression = stringExpression;
            this.stringOrderBy = stringOrderBy;
            this.intRecordFrom = intRecordFrom;
            this.intRecordTo = intRecordTo;
            this.objDataSetStringInfo = objDataSetStringInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListSMSDetailsR1V1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListSMSDetailsR1V1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ListSMSDetailsR1V1Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int intRecordCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] stringOutputResult;
        
        public ListSMSDetailsR1V1Response() {
        }
        
        public ListSMSDetailsR1V1Response(System.Data.DataSet ListSMSDetailsR1V1Result, int intRecordCount, int intErrorCount, string[] stringOutputResult) {
            this.ListSMSDetailsR1V1Result = ListSMSDetailsR1V1Result;
            this.intRecordCount = intRecordCount;
            this.intErrorCount = intErrorCount;
            this.stringOutputResult = stringOutputResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListSMSDetailsR2V1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListSMSDetailsR2V1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] stringInputValues;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string stringType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string stringExpression;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string stringOrderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int intRecordFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int intRecordTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public System.Data.DataSet objDataSetStringInfo;
        
        public ListSMSDetailsR2V1Request() {
        }
        
        public ListSMSDetailsR2V1Request(string[] stringInputValues, string stringType, string stringExpression, string stringOrderBy, int intRecordFrom, int intRecordTo, System.Data.DataSet objDataSetStringInfo) {
            this.stringInputValues = stringInputValues;
            this.stringType = stringType;
            this.stringExpression = stringExpression;
            this.stringOrderBy = stringOrderBy;
            this.intRecordFrom = intRecordFrom;
            this.intRecordTo = intRecordTo;
            this.objDataSetStringInfo = objDataSetStringInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListSMSDetailsR2V1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListSMSDetailsR2V1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ListSMSDetailsR2V1Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int intRecordCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] stringOutputResult;
        
        public ListSMSDetailsR2V1Response() {
        }
        
        public ListSMSDetailsR2V1Response(System.Data.DataSet ListSMSDetailsR2V1Result, int intRecordCount, int intErrorCount, string[] stringOutputResult) {
            this.ListSMSDetailsR2V1Result = ListSMSDetailsR2V1Result;
            this.intRecordCount = intRecordCount;
            this.intErrorCount = intErrorCount;
            this.stringOutputResult = stringOutputResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToExcelLastRecordR1V1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExportToExcelLastRecordR1V1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string stringId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string stringExportname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Data.DataSet objDataSetStringInfo;
        
        public ExportToExcelLastRecordR1V1Request() {
        }
        
        public ExportToExcelLastRecordR1V1Request(string stringId, string stringExportname, System.Data.DataSet objDataSetStringInfo) {
            this.stringId = stringId;
            this.stringExportname = stringExportname;
            this.objDataSetStringInfo = objDataSetStringInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportToExcelLastRecordR1V1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExportToExcelLastRecordR1V1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ExportToExcelLastRecordR1V1Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte[] objbyteArray;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] stringOutputResult;
        
        public ExportToExcelLastRecordR1V1Response() {
        }
        
        public ExportToExcelLastRecordR1V1Response(string ExportToExcelLastRecordR1V1Result, byte[] objbyteArray, int intErrorCount, string[] stringOutputResult) {
            this.ExportToExcelLastRecordR1V1Result = ExportToExcelLastRecordR1V1Result;
            this.objbyteArray = objbyteArray;
            this.intErrorCount = intErrorCount;
            this.stringOutputResult = stringOutputResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportCommonWindowToExcelR1V1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExportCommonWindowToExcelR1V1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string stringFunctionName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string stringExpression;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string stringOrderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string stringExportName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public System.Data.DataSet objDataSetStringInfo;
        
        public ExportCommonWindowToExcelR1V1Request() {
        }
        
        public ExportCommonWindowToExcelR1V1Request(string stringFunctionName, string stringExpression, string stringOrderBy, string stringExportName, System.Data.DataSet objDataSetStringInfo) {
            this.stringFunctionName = stringFunctionName;
            this.stringExpression = stringExpression;
            this.stringOrderBy = stringOrderBy;
            this.stringExportName = stringExportName;
            this.objDataSetStringInfo = objDataSetStringInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportCommonWindowToExcelR1V1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExportCommonWindowToExcelR1V1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ExportCommonWindowToExcelR1V1Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte[] objbyteArray;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] stringOutputResult;
        
        public ExportCommonWindowToExcelR1V1Response() {
        }
        
        public ExportCommonWindowToExcelR1V1Response(string ExportCommonWindowToExcelR1V1Result, byte[] objbyteArray, int intErrorCount, string[] stringOutputResult) {
            this.ExportCommonWindowToExcelR1V1Result = ExportCommonWindowToExcelR1V1Result;
            this.objbyteArray = objbyteArray;
            this.intErrorCount = intErrorCount;
            this.stringOutputResult = stringOutputResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportSearchToExcelR1V1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExportSearchToExcelR1V1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string stringFunctionName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string stringExpression;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string stringOrderBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string stringExportName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public System.Data.DataSet objDataSetStringInfo;
        
        public ExportSearchToExcelR1V1Request() {
        }
        
        public ExportSearchToExcelR1V1Request(string stringFunctionName, string stringExpression, string stringOrderBy, string stringExportName, System.Data.DataSet objDataSetStringInfo) {
            this.stringFunctionName = stringFunctionName;
            this.stringExpression = stringExpression;
            this.stringOrderBy = stringOrderBy;
            this.stringExportName = stringExportName;
            this.objDataSetStringInfo = objDataSetStringInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportSearchToExcelR1V1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExportSearchToExcelR1V1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ExportSearchToExcelR1V1Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte[] objbyteArray;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int intErrorCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] stringOutputResult;
        
        public ExportSearchToExcelR1V1Response() {
        }
        
        public ExportSearchToExcelR1V1Response(string ExportSearchToExcelR1V1Result, byte[] objbyteArray, int intErrorCount, string[] stringOutputResult) {
            this.ExportSearchToExcelR1V1Result = ExportSearchToExcelR1V1Result;
            this.objbyteArray = objbyteArray;
            this.intErrorCount = intErrorCount;
            this.stringOutputResult = stringOutputResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISMSSERVICEChannel : WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSSERVICEClient : System.ServiceModel.ClientBase<WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE>, WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE {
        
        public SMSSERVICEClient() {
        }
        
        public SMSSERVICEClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSSERVICEClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSSERVICEClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSSERVICEClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_In_ConsoleApp.GSSMSService.DataManipulationR1V1Response WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE.DataManipulationR1V1(WCF_In_ConsoleApp.GSSMSService.DataManipulationR1V1Request request) {
            return base.Channel.DataManipulationR1V1(request);
        }
        
        public System.Data.DataSet DataManipulationR1V1(System.Data.DataSet objDataSet, System.Data.DataSet objDataSetStringInfo, out int intErrorCount, out string[] stringOutputResult) {
            WCF_In_ConsoleApp.GSSMSService.DataManipulationR1V1Request inValue = new WCF_In_ConsoleApp.GSSMSService.DataManipulationR1V1Request();
            inValue.objDataSet = objDataSet;
            inValue.objDataSetStringInfo = objDataSetStringInfo;
            WCF_In_ConsoleApp.GSSMSService.DataManipulationR1V1Response retVal = ((WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE)(this)).DataManipulationR1V1(inValue);
            intErrorCount = retVal.intErrorCount;
            stringOutputResult = retVal.stringOutputResult;
            return retVal.DataManipulationR1V1Result;
        }
        
        public System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.DataManipulationR1V1Response> DataManipulationR1V1Async(WCF_In_ConsoleApp.GSSMSService.DataManipulationR1V1Request request) {
            return base.Channel.DataManipulationR1V1Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_In_ConsoleApp.GSSMSService.List1R1V1Response WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE.List1R1V1(WCF_In_ConsoleApp.GSSMSService.List1R1V1Request request) {
            return base.Channel.List1R1V1(request);
        }
        
        public System.Data.DataSet List1R1V1(string stringExpression, string stringOrderBy, int intRecordFrom, int intRecordTo, System.Data.DataSet objDataSetStringInfo, out int intRecordCount, out int intErrorCount, out string[] stringOutputResult) {
            WCF_In_ConsoleApp.GSSMSService.List1R1V1Request inValue = new WCF_In_ConsoleApp.GSSMSService.List1R1V1Request();
            inValue.stringExpression = stringExpression;
            inValue.stringOrderBy = stringOrderBy;
            inValue.intRecordFrom = intRecordFrom;
            inValue.intRecordTo = intRecordTo;
            inValue.objDataSetStringInfo = objDataSetStringInfo;
            WCF_In_ConsoleApp.GSSMSService.List1R1V1Response retVal = ((WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE)(this)).List1R1V1(inValue);
            intRecordCount = retVal.intRecordCount;
            intErrorCount = retVal.intErrorCount;
            stringOutputResult = retVal.stringOutputResult;
            return retVal.List1R1V1Result;
        }
        
        public System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.List1R1V1Response> List1R1V1Async(WCF_In_ConsoleApp.GSSMSService.List1R1V1Request request) {
            return base.Channel.List1R1V1Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_In_ConsoleApp.GSSMSService.List2R1V1Response WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE.List2R1V1(WCF_In_ConsoleApp.GSSMSService.List2R1V1Request request) {
            return base.Channel.List2R1V1(request);
        }
        
        public System.Data.DataSet List2R1V1(string stringExpression, string stringOrderBy, int intRecordFrom, int intRecordTo, System.Data.DataSet objDataSetStringInfo, out int intRecordCount, out int intErrorCount, out string[] stringOutputResult) {
            WCF_In_ConsoleApp.GSSMSService.List2R1V1Request inValue = new WCF_In_ConsoleApp.GSSMSService.List2R1V1Request();
            inValue.stringExpression = stringExpression;
            inValue.stringOrderBy = stringOrderBy;
            inValue.intRecordFrom = intRecordFrom;
            inValue.intRecordTo = intRecordTo;
            inValue.objDataSetStringInfo = objDataSetStringInfo;
            WCF_In_ConsoleApp.GSSMSService.List2R1V1Response retVal = ((WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE)(this)).List2R1V1(inValue);
            intRecordCount = retVal.intRecordCount;
            intErrorCount = retVal.intErrorCount;
            stringOutputResult = retVal.stringOutputResult;
            return retVal.List2R1V1Result;
        }
        
        public System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.List2R1V1Response> List2R1V1Async(WCF_In_ConsoleApp.GSSMSService.List2R1V1Request request) {
            return base.Channel.List2R1V1Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_In_ConsoleApp.GSSMSService.List3R1V1Response WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE.List3R1V1(WCF_In_ConsoleApp.GSSMSService.List3R1V1Request request) {
            return base.Channel.List3R1V1(request);
        }
        
        public System.Data.DataSet List3R1V1(string stringExpression, string stringOrderBy, int intRecordFrom, int intRecordTo, System.Data.DataSet objDataSetStringInfo, out int intRecordCount, out int intErrorCount, out string[] stringOutputResult) {
            WCF_In_ConsoleApp.GSSMSService.List3R1V1Request inValue = new WCF_In_ConsoleApp.GSSMSService.List3R1V1Request();
            inValue.stringExpression = stringExpression;
            inValue.stringOrderBy = stringOrderBy;
            inValue.intRecordFrom = intRecordFrom;
            inValue.intRecordTo = intRecordTo;
            inValue.objDataSetStringInfo = objDataSetStringInfo;
            WCF_In_ConsoleApp.GSSMSService.List3R1V1Response retVal = ((WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE)(this)).List3R1V1(inValue);
            intRecordCount = retVal.intRecordCount;
            intErrorCount = retVal.intErrorCount;
            stringOutputResult = retVal.stringOutputResult;
            return retVal.List3R1V1Result;
        }
        
        public System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.List3R1V1Response> List3R1V1Async(WCF_In_ConsoleApp.GSSMSService.List3R1V1Request request) {
            return base.Channel.List3R1V1Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_In_ConsoleApp.GSSMSService.List4R1V1Response WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE.List4R1V1(WCF_In_ConsoleApp.GSSMSService.List4R1V1Request request) {
            return base.Channel.List4R1V1(request);
        }
        
        public System.Data.DataSet List4R1V1(string stringExpression, string stringOrderBy, int intRecordFrom, int intRecordTo, System.Data.DataSet objDataSetStringInfo, out int intRecordCount, out int intErrorCount, out string[] stringOutputResult) {
            WCF_In_ConsoleApp.GSSMSService.List4R1V1Request inValue = new WCF_In_ConsoleApp.GSSMSService.List4R1V1Request();
            inValue.stringExpression = stringExpression;
            inValue.stringOrderBy = stringOrderBy;
            inValue.intRecordFrom = intRecordFrom;
            inValue.intRecordTo = intRecordTo;
            inValue.objDataSetStringInfo = objDataSetStringInfo;
            WCF_In_ConsoleApp.GSSMSService.List4R1V1Response retVal = ((WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE)(this)).List4R1V1(inValue);
            intRecordCount = retVal.intRecordCount;
            intErrorCount = retVal.intErrorCount;
            stringOutputResult = retVal.stringOutputResult;
            return retVal.List4R1V1Result;
        }
        
        public System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.List4R1V1Response> List4R1V1Async(WCF_In_ConsoleApp.GSSMSService.List4R1V1Request request) {
            return base.Channel.List4R1V1Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_In_ConsoleApp.GSSMSService.List5R1V1Response WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE.List5R1V1(WCF_In_ConsoleApp.GSSMSService.List5R1V1Request request) {
            return base.Channel.List5R1V1(request);
        }
        
        public System.Data.DataSet List5R1V1(string stringExpression, string stringOrderBy, int intRecordFrom, int intRecordTo, System.Data.DataSet objDataSetStringInfo, out int intRecordCount, out int intErrorCount, out string[] stringOutputResult) {
            WCF_In_ConsoleApp.GSSMSService.List5R1V1Request inValue = new WCF_In_ConsoleApp.GSSMSService.List5R1V1Request();
            inValue.stringExpression = stringExpression;
            inValue.stringOrderBy = stringOrderBy;
            inValue.intRecordFrom = intRecordFrom;
            inValue.intRecordTo = intRecordTo;
            inValue.objDataSetStringInfo = objDataSetStringInfo;
            WCF_In_ConsoleApp.GSSMSService.List5R1V1Response retVal = ((WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE)(this)).List5R1V1(inValue);
            intRecordCount = retVal.intRecordCount;
            intErrorCount = retVal.intErrorCount;
            stringOutputResult = retVal.stringOutputResult;
            return retVal.List5R1V1Result;
        }
        
        public System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.List5R1V1Response> List5R1V1Async(WCF_In_ConsoleApp.GSSMSService.List5R1V1Request request) {
            return base.Channel.List5R1V1Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_In_ConsoleApp.GSSMSService.ListRecordCountR1V1Response WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE.ListRecordCountR1V1(WCF_In_ConsoleApp.GSSMSService.ListRecordCountR1V1Request request) {
            return base.Channel.ListRecordCountR1V1(request);
        }
        
        public System.Data.DataSet ListRecordCountR1V1(string tableName, string stringExpression, string condition, System.Data.DataSet objDataSetStringInfo, out int intRecordCount, out int intErrorCount, out string[] stringOutputResult) {
            WCF_In_ConsoleApp.GSSMSService.ListRecordCountR1V1Request inValue = new WCF_In_ConsoleApp.GSSMSService.ListRecordCountR1V1Request();
            inValue.tableName = tableName;
            inValue.stringExpression = stringExpression;
            inValue.condition = condition;
            inValue.objDataSetStringInfo = objDataSetStringInfo;
            WCF_In_ConsoleApp.GSSMSService.ListRecordCountR1V1Response retVal = ((WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE)(this)).ListRecordCountR1V1(inValue);
            intRecordCount = retVal.intRecordCount;
            intErrorCount = retVal.intErrorCount;
            stringOutputResult = retVal.stringOutputResult;
            return retVal.ListRecordCountR1V1Result;
        }
        
        public System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.ListRecordCountR1V1Response> ListRecordCountR1V1Async(WCF_In_ConsoleApp.GSSMSService.ListRecordCountR1V1Request request) {
            return base.Channel.ListRecordCountR1V1Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_In_ConsoleApp.GSSMSService.ListR2V1Response WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE.ListR2V1(WCF_In_ConsoleApp.GSSMSService.ListR2V1Request request) {
            return base.Channel.ListR2V1(request);
        }
        
        public System.Data.DataSet ListR2V1(string[] stringInputValues, string stringExpression, string stringOrderBy, int intRecordFrom, int intRecordTo, System.Data.DataSet objDataSetStringInfo, out int intRecordCount, out int intErrorCount, out string[] stringOutputResult) {
            WCF_In_ConsoleApp.GSSMSService.ListR2V1Request inValue = new WCF_In_ConsoleApp.GSSMSService.ListR2V1Request();
            inValue.stringInputValues = stringInputValues;
            inValue.stringExpression = stringExpression;
            inValue.stringOrderBy = stringOrderBy;
            inValue.intRecordFrom = intRecordFrom;
            inValue.intRecordTo = intRecordTo;
            inValue.objDataSetStringInfo = objDataSetStringInfo;
            WCF_In_ConsoleApp.GSSMSService.ListR2V1Response retVal = ((WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE)(this)).ListR2V1(inValue);
            intRecordCount = retVal.intRecordCount;
            intErrorCount = retVal.intErrorCount;
            stringOutputResult = retVal.stringOutputResult;
            return retVal.ListR2V1Result;
        }
        
        public System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.ListR2V1Response> ListR2V1Async(WCF_In_ConsoleApp.GSSMSService.ListR2V1Request request) {
            return base.Channel.ListR2V1Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsResponse WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE.UpdateSMSDetails(WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsRequest request) {
            return base.Channel.UpdateSMSDetails(request);
        }
        
        public System.Data.DataSet UpdateSMSDetails(string stringType, string[] stringInputValues, System.Data.DataSet objDataSetInput, System.Data.DataSet objDataSetStringInfo, out int intErrorCount, out string[] stringOutputResult) {
            WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsRequest inValue = new WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsRequest();
            inValue.stringType = stringType;
            inValue.stringInputValues = stringInputValues;
            inValue.objDataSetInput = objDataSetInput;
            inValue.objDataSetStringInfo = objDataSetStringInfo;
            WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsResponse retVal = ((WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE)(this)).UpdateSMSDetails(inValue);
            intErrorCount = retVal.intErrorCount;
            stringOutputResult = retVal.stringOutputResult;
            return retVal.UpdateSMSDetailsResult;
        }
        
        public System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsResponse> UpdateSMSDetailsAsync(WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsRequest request) {
            return base.Channel.UpdateSMSDetailsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsR1V1Response WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE.UpdateSMSDetailsR1V1(WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsR1V1Request request) {
            return base.Channel.UpdateSMSDetailsR1V1(request);
        }
        
        public System.Data.DataSet UpdateSMSDetailsR1V1(string stringType, string[] stringInputValues, System.Data.DataSet objDataSetInput, System.Data.DataSet objDataSetStringInfo, out int intErrorCount, out string[] stringOutputResult) {
            WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsR1V1Request inValue = new WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsR1V1Request();
            inValue.stringType = stringType;
            inValue.stringInputValues = stringInputValues;
            inValue.objDataSetInput = objDataSetInput;
            inValue.objDataSetStringInfo = objDataSetStringInfo;
            WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsR1V1Response retVal = ((WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE)(this)).UpdateSMSDetailsR1V1(inValue);
            intErrorCount = retVal.intErrorCount;
            stringOutputResult = retVal.stringOutputResult;
            return retVal.UpdateSMSDetailsR1V1Result;
        }
        
        public System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsR1V1Response> UpdateSMSDetailsR1V1Async(WCF_In_ConsoleApp.GSSMSService.UpdateSMSDetailsR1V1Request request) {
            return base.Channel.UpdateSMSDetailsR1V1Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR1V1Response WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE.ListSMSDetailsR1V1(WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR1V1Request request) {
            return base.Channel.ListSMSDetailsR1V1(request);
        }
        
        public System.Data.DataSet ListSMSDetailsR1V1(string stringType, string stringExpression, string stringOrderBy, int intRecordFrom, int intRecordTo, System.Data.DataSet objDataSetStringInfo, out int intRecordCount, out int intErrorCount, out string[] stringOutputResult) {
            WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR1V1Request inValue = new WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR1V1Request();
            inValue.stringType = stringType;
            inValue.stringExpression = stringExpression;
            inValue.stringOrderBy = stringOrderBy;
            inValue.intRecordFrom = intRecordFrom;
            inValue.intRecordTo = intRecordTo;
            inValue.objDataSetStringInfo = objDataSetStringInfo;
            WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR1V1Response retVal = ((WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE)(this)).ListSMSDetailsR1V1(inValue);
            intRecordCount = retVal.intRecordCount;
            intErrorCount = retVal.intErrorCount;
            stringOutputResult = retVal.stringOutputResult;
            return retVal.ListSMSDetailsR1V1Result;
        }
        
        public System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR1V1Response> ListSMSDetailsR1V1Async(WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR1V1Request request) {
            return base.Channel.ListSMSDetailsR1V1Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR2V1Response WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE.ListSMSDetailsR2V1(WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR2V1Request request) {
            return base.Channel.ListSMSDetailsR2V1(request);
        }
        
        public System.Data.DataSet ListSMSDetailsR2V1(string[] stringInputValues, string stringType, string stringExpression, string stringOrderBy, int intRecordFrom, int intRecordTo, System.Data.DataSet objDataSetStringInfo, out int intRecordCount, out int intErrorCount, out string[] stringOutputResult) {
            WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR2V1Request inValue = new WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR2V1Request();
            inValue.stringInputValues = stringInputValues;
            inValue.stringType = stringType;
            inValue.stringExpression = stringExpression;
            inValue.stringOrderBy = stringOrderBy;
            inValue.intRecordFrom = intRecordFrom;
            inValue.intRecordTo = intRecordTo;
            inValue.objDataSetStringInfo = objDataSetStringInfo;
            WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR2V1Response retVal = ((WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE)(this)).ListSMSDetailsR2V1(inValue);
            intRecordCount = retVal.intRecordCount;
            intErrorCount = retVal.intErrorCount;
            stringOutputResult = retVal.stringOutputResult;
            return retVal.ListSMSDetailsR2V1Result;
        }
        
        public System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR2V1Response> ListSMSDetailsR2V1Async(WCF_In_ConsoleApp.GSSMSService.ListSMSDetailsR2V1Request request) {
            return base.Channel.ListSMSDetailsR2V1Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_In_ConsoleApp.GSSMSService.ExportToExcelLastRecordR1V1Response WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE.ExportToExcelLastRecordR1V1(WCF_In_ConsoleApp.GSSMSService.ExportToExcelLastRecordR1V1Request request) {
            return base.Channel.ExportToExcelLastRecordR1V1(request);
        }
        
        public string ExportToExcelLastRecordR1V1(string stringId, string stringExportname, System.Data.DataSet objDataSetStringInfo, out byte[] objbyteArray, out int intErrorCount, out string[] stringOutputResult) {
            WCF_In_ConsoleApp.GSSMSService.ExportToExcelLastRecordR1V1Request inValue = new WCF_In_ConsoleApp.GSSMSService.ExportToExcelLastRecordR1V1Request();
            inValue.stringId = stringId;
            inValue.stringExportname = stringExportname;
            inValue.objDataSetStringInfo = objDataSetStringInfo;
            WCF_In_ConsoleApp.GSSMSService.ExportToExcelLastRecordR1V1Response retVal = ((WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE)(this)).ExportToExcelLastRecordR1V1(inValue);
            objbyteArray = retVal.objbyteArray;
            intErrorCount = retVal.intErrorCount;
            stringOutputResult = retVal.stringOutputResult;
            return retVal.ExportToExcelLastRecordR1V1Result;
        }
        
        public System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.ExportToExcelLastRecordR1V1Response> ExportToExcelLastRecordR1V1Async(WCF_In_ConsoleApp.GSSMSService.ExportToExcelLastRecordR1V1Request request) {
            return base.Channel.ExportToExcelLastRecordR1V1Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_In_ConsoleApp.GSSMSService.ExportCommonWindowToExcelR1V1Response WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE.ExportCommonWindowToExcelR1V1(WCF_In_ConsoleApp.GSSMSService.ExportCommonWindowToExcelR1V1Request request) {
            return base.Channel.ExportCommonWindowToExcelR1V1(request);
        }
        
        public string ExportCommonWindowToExcelR1V1(string stringFunctionName, string stringExpression, string stringOrderBy, string stringExportName, System.Data.DataSet objDataSetStringInfo, out byte[] objbyteArray, out int intErrorCount, out string[] stringOutputResult) {
            WCF_In_ConsoleApp.GSSMSService.ExportCommonWindowToExcelR1V1Request inValue = new WCF_In_ConsoleApp.GSSMSService.ExportCommonWindowToExcelR1V1Request();
            inValue.stringFunctionName = stringFunctionName;
            inValue.stringExpression = stringExpression;
            inValue.stringOrderBy = stringOrderBy;
            inValue.stringExportName = stringExportName;
            inValue.objDataSetStringInfo = objDataSetStringInfo;
            WCF_In_ConsoleApp.GSSMSService.ExportCommonWindowToExcelR1V1Response retVal = ((WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE)(this)).ExportCommonWindowToExcelR1V1(inValue);
            objbyteArray = retVal.objbyteArray;
            intErrorCount = retVal.intErrorCount;
            stringOutputResult = retVal.stringOutputResult;
            return retVal.ExportCommonWindowToExcelR1V1Result;
        }
        
        public System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.ExportCommonWindowToExcelR1V1Response> ExportCommonWindowToExcelR1V1Async(WCF_In_ConsoleApp.GSSMSService.ExportCommonWindowToExcelR1V1Request request) {
            return base.Channel.ExportCommonWindowToExcelR1V1Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCF_In_ConsoleApp.GSSMSService.ExportSearchToExcelR1V1Response WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE.ExportSearchToExcelR1V1(WCF_In_ConsoleApp.GSSMSService.ExportSearchToExcelR1V1Request request) {
            return base.Channel.ExportSearchToExcelR1V1(request);
        }
        
        public string ExportSearchToExcelR1V1(string stringFunctionName, string stringExpression, string stringOrderBy, string stringExportName, System.Data.DataSet objDataSetStringInfo, out byte[] objbyteArray, out int intErrorCount, out string[] stringOutputResult) {
            WCF_In_ConsoleApp.GSSMSService.ExportSearchToExcelR1V1Request inValue = new WCF_In_ConsoleApp.GSSMSService.ExportSearchToExcelR1V1Request();
            inValue.stringFunctionName = stringFunctionName;
            inValue.stringExpression = stringExpression;
            inValue.stringOrderBy = stringOrderBy;
            inValue.stringExportName = stringExportName;
            inValue.objDataSetStringInfo = objDataSetStringInfo;
            WCF_In_ConsoleApp.GSSMSService.ExportSearchToExcelR1V1Response retVal = ((WCF_In_ConsoleApp.GSSMSService.ISMSSERVICE)(this)).ExportSearchToExcelR1V1(inValue);
            objbyteArray = retVal.objbyteArray;
            intErrorCount = retVal.intErrorCount;
            stringOutputResult = retVal.stringOutputResult;
            return retVal.ExportSearchToExcelR1V1Result;
        }
        
        public System.Threading.Tasks.Task<WCF_In_ConsoleApp.GSSMSService.ExportSearchToExcelR1V1Response> ExportSearchToExcelR1V1Async(WCF_In_ConsoleApp.GSSMSService.ExportSearchToExcelR1V1Request request) {
            return base.Channel.ExportSearchToExcelR1V1Async(request);
        }
    }
}
